### PR TITLE
Tomer fixes

### PR DESCRIPTION
**Pull request by tomers**
Some more improvements. Mainly separation of code, and create helper classes.

### CODE REVIEW

**Comment by maresb** [comment]
Excellent as usual, thanks @tomers!!!

When I ran it I hit some exceptions, e.g. with `super` and `Path` vs `str`. I fixed them in my suggestions here: https://github.com/tomers/dymoprint/pull/2

If you feel so motivated, it would be nice to get rid of that `die` function, it feels very Perl. :joy: 

Are you familiar with `mypy`? It'd be amazing to have this code statically type-checked.

**Comment by maresb** [comment]
See also https://github.com/tomers/dymoprint/pull/3

**Comment by maresb** [comment]
And mypy: https://github.com/tomers/dymoprint/pull/4

**Comment by tomers** [comment]
Thank you so much @maresb ! It's really a pleasure to work with you. You are very responsive and helpful.
You contribute a lot in a to my PRs, in a timely manner, and I got to learn a lot from you :heart: 
Thanks!

**Comment by maresb** [comment]
Likewise!!! I'm very happy to have your energy and enthusiasm to move things so far forward here! The codebase is in much better shape since you came along.

**Pull request merged**
