### PR TITLE
Add DYMO LabelMANAGER PC to tested devices

### PR DESCRIPTION
**Pull request by jbruechert**
Add DYMO LabelMANAGER PC to tested devices

### CODE REVIEW

**Comment by maresb** [comment]
Thanks @JBBgameich !

Is this the product?
https://www.newegg.com/dymo-labelmanager-pc-ii-18949/p/N82E16828111019

I am finding very little information about it. Where did you buy it? Is it new or old? Also it looks like it's called "PC II" even though the device itself says just "PC"? Just trying to understand.

Also could you please give a brief description of what you did? You added this 0x11 to the list and it was recognized and able to print?

Thanks again!

**Comment by jbruechert** [comment]
We still had this laying around in my hackerspace and tried to get it working again yesterday.
I think it is the PC I version, but there are pictures of the PC II one without the II symbol printed on it online, so I'm not 100% sure.

After some time of fiddling with the original Windows XP driver we eventually just tried to use your application, and it just worked and was able to print QR codes and text labels successfully.

The device was even recognized before adding it to the list, but with a notice of being untested or similar.

**Comment by maresb** [comment]
Oh awesome! Are you using this under Windows? If so, how was your experience?

**Comment by jbruechert** [comment]
I tested it on Linux in the end. The Windows XP VM was just for testing the original driver.

**Comment by maresb** [comment]
@JBBgameich, do you have any ideas what could be going on in #93? Would it be possible to verify that your device still prints with the latest version?

**Comment by jbruechert** [comment]
It still works :)

**Pull request merged**
