### PR TITLE
added / activated tape size selector

### PR DESCRIPTION
**Pull request by fabianhu**
Just quickly checked the different tape sizes.
The height offset was determined by experimentation.
QR only checked for 12mm.

Could someone check, if barcodes still work?

### CODE REVIEW

**Comment by computerlyrik** [comment]
Thank you for your work. 
Due to multiple changes, it will take some time to know if all use cases work.
I will test mine as soon as i need lables again.

Feedback from other users welcome!

**Comment by varac** [comment]
@fabianhu could you please fix the merge conflict ? I'd like to give this PR a test.
@computerlyrik Do you mind reviewing and merging ?

**Comment by maresb** [comment]
Hi @fabianhu, this seems to be abandoned, but I'm happy to accept PRs at https://github.com/maresb/dymoprint

**Comment by Tahx** [comment]
@maresb I'm trying to get it to work for the Dymo MobileLabeler but I can't get it to be recognized by the program.

> The device 'Dymo LabelManager PnP' could not be found on this system.


The vendor ID is the same as the PnP and the ProductId is 1009, I'm not sure what to insert instead of "1002" inside the 91 named file.

Sadly I have that feeling it is a waste of time and won't work, I wished to remove that gigantic 1cm margin on both sides that's wasting such a ton of label...

**Comment by maresb** [comment]
@Tahx interesting. So it's Bluetooth? It looks similar, so it does seem like it should work in theory. I am on the road at the moment, so I can't do much right now, but it would be nice to see if we could get it to work.

**Comment by Tahx** [comment]
@maresb I ended up cloning your fork and setting the filepath of the usb bus inside the constant file, but it crash at reading the response of what I suppose it to be the command to write a label.

Yes it also has bluetooth connectivity on top of USB, and it has an Android app so it should be possibly easier to reverse than USB.

I'll have no choice but to take time to reverse it, there aren't many autocut label writers and they all waste too much labels in a way or another.

I think I'd like to give this rep a very last try to check if it's really a different protocol.

Do you have a MobileLabeler aswell?

**Comment by maresb** [comment]
Discussion moved to https://github.com/maresb/dymoprint/issues/1

**Comment by computerlyrik** [comment]
@maresb @Tahx
Sorry for the late response, invited you two as project collaborators.

I plan to give as many rights as possible for this repo so you can do whatever you like - i am very sorry i have no time to support this repository anymore.

Thanks for continuing work - i am really sorry i never found the time to get deeper into all the issues opened here.

I am very happy lifting the code to github went so successful and helped some ppl in need.

**Comment by maresb** [comment]
Hi @computerlyrik, great to finally hear from you! I am on the road at the moment, but if you don't object, at some point in the coming days/weeks I'll merge my fork so that this repo is the home.

**Comment by maresb** [comment]
@Tahx, I just realized that someone else is working on the MobileLabeler here in #30. Did you ever manage to find a solution?

By the way, I made a suggestion in https://github.com/computerlyrik/dymoprint/issues/30#issuecomment-984793370 about what how to replace the device ID `1002`. (Sorry that I didn't think of that idea when you asked.)

**Comment by maresb** [comment]
Closing as stale

**Pull request closed without merging**
